spring:
  data:
    mongodb:
      uri: mongodb+srv://도메인.mongodb.net/?retryWrites=true&w=majority
      database: 디비
      username: 유저
      password: 비번

  mail:
    host: smtp.gmail.com
    port: 587
    username: a@gmail.com
    password: '1234 abcd'
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  issuer: 이슈
  secret_key: 키
  # openssl rand -hex 32

logging:
  level:
    org:
      springframework:
        security: DEBUG

unprotected:
  routes: /login,/user/signup

cloud:
  aws:
    s3:
      bucket: beautyminder-sw
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      access-key: ""
      secret-key: ""

aws:
  os:
    region: "ap-northeast-2"
    endpoint: "es.amazonaws.com:443"

chatgpt:
  api-key: sk-
  model: gpt-4
  multi:
    model: gpt-4
    max-tokens: 512
  system: blah